### ISSUE TITLE
DB Scheme

### ISSUE THREAD

**Issue by diegofcoelho** [jsarcher/zilgraph#2]
Can you release the structure for the database?

**Comment by rustyqt** [comment]
Recently, there has been a major shift in the Zilgraph back-end towards elasticsearch. Currently I have two indexes, zilcrawl and zilswap.

zilcrawl: Here you have all transactions executed at the Zilliqa blockchain. Some fields, e.g. events, are saved as serialized strings so that it was possible to store all transactions in a simple and common manner without pre-filtering.

zilswap: The zilswap.py contiounsly searches for new transaction in the zilcrawl index. If any zilswap related transactions appear, the data gets analyzed and the aggregated data gets stored in the zilswap index. 

For the database structure you can have a look directly in kibana. At port 5602 you get logged in automatically as a read-only user and you can explore the data on your own. See: https://zilgraph.io:5602

**Comment by rustyqt** [comment]
Database publicly available.
